### ISSUE TITLE
dates file generated but empty

### ISSUE THREAD

**Issue by bpluhar** [mavrk/github-graffiti#2]
After creating a quick little design, I right click and enter a date for when I want it to show, the `dates.txt` gets generated but the file is empty.

**Comment by mavrk** [comment]
Can you try running the program from a console? That way we could tell if it throws some exception.

**Comment by bpluhar** [comment]
Running it from CL, I right click and enter today's date `20/09/2018`, and the console echo's the squares that I selected. Here's the output:

17/09/2017
13/11/2017/1
30/11/2017/1
06/12/2017/1
26/12/2017/1
24/01/2018/1
30/01/2018/1
09/02/2018/1
02/03/2018/1
06/03/2018/1
07/03/2018/1
09/03/2018/1
13/03/2018/1
03/04/2018/1
18/04/2018/1
10/05/2018/1
22/05/2018/1
29/05/2018/1

Edit: And `dates.txt` is still empty. Could I just copy that output in the console to `dates.txt` and then run `paint.sh`?

**Comment by mavrk** [comment]
Yes, the console's output is the exact same thing. I am not sure why it wasn't written in the file dates.txt

**Comment by mavrk** [comment]
Also, please ignore the first line of the console (17/09/2017 in this case). That was just a debug info and it is not part of dates.txt

**Comment by bpluhar** [comment]
Hey @mavrk, sorry for the late response, been out of town.

With ignoring the first line as you stated, I pasted the rest of the dates into `dates.txt` and ran `paint.sh` and it all worked great! Took a little over a day for the commits to show and line up properly but it works!

Thanks for the help!

**Comment by mavrk** [comment]
[FIXED] .jar file was buggy and now replaced with the updated .jar file
